import { shipmentRepository } from '../repositories/shipmentRepository';
import { orderRepository } from '../repositories/orderRepository';
import { prisma } from '../config/prisma';
import { CreateShipmentInput, UpdateShipmentStatusInput, ConfirmDeliveryInput } from '../validators/shipmentValidators';
import { logAuditEvent } from '../utils/auditLogger';
import { ShipmentStatus, OrderStatus, NotificationType } from '@prisma/client';
import { notificationService } from './notificationService';

export class ShipmentService {
  async createShipment(userId: string, sellerId: string, orderItemId: string, input: CreateShipmentInput, ipAddress?: string) {
    const orderItem = await prisma.orderItem.findUnique({
      where: { id: orderItemId },
      include: { order: true },
    });

    if (!orderItem || orderItem.sellerId !== sellerId) {
      const error: any = new Error('Order item not found or unauthorized.');
      error.statusCode = 403;
      error.code = 'FORBIDDEN';
      throw error;
    }

    const estimatedDate = input.estimatedDeliveryDate ? new Date(input.estimatedDeliveryDate) : undefined;

    const shipment = await shipmentRepository.createShipment({
      orderId: orderItem.orderId,
      sellerId,
      shippingMethod: input.shippingMethod,
      courierPartner: input.courierPartner,
      trackingNumber: input.trackingNumber,
      estimatedDeliveryDate: estimatedDate,
      initialNote: input.initialNote,
    });

    // Transition Order status if appropriate
    if (orderItem.order.status === OrderStatus.PAID_ESCROW || orderItem.order.status === OrderStatus.PAYMENT_PENDING) {
      await orderRepository.updateOrderStatus(orderItem.orderId, OrderStatus.SELLER_ACCEPTED, userId, 'Shipment record generated by seller.');
    }

    // Trigger Notification for Buyer
    await notificationService.notifyUser({
      userId: orderItem.order.buyerId,
      type: NotificationType.SHIPMENT_CREATED,
      title: `🚚 Shipment Created: #${shipment.shipmentNumber}`,
      body: `Your order item "${orderItem.snapshotTitle}" has been prepared for shipping via ${shipment.courierPartner || 'seller delivery'}.`,
      data: { orderNumber: orderItem.order.orderNumber, shipmentNumber: shipment.shipmentNumber },
      actionUrl: `/orders/${orderItem.order.orderNumber}/tracking`,
    });

    await logAuditEvent('SHIPMENT_CREATED', 'Shipment', userId, shipment.id, { shipmentNumber: shipment.shipmentNumber }, ipAddress);
    return shipment;
  }

  async updateShipmentStatus(userId: string, sellerId: string, shipmentId: string, input: UpdateShipmentStatusInput, ipAddress?: string) {
    const shipment = await shipmentRepository.findShipmentById(shipmentId);

    if (!shipment || shipment.sellerId !== sellerId) {
      const error: any = new Error('Shipment not found or unauthorized.');
      error.statusCode = 403;
      error.code = 'FORBIDDEN';
      throw error;
    }

    // Controlled Status Transitions
    const allowedTransitions: Record<string, ShipmentStatus[]> = {
      PENDING: [ShipmentStatus.READY_FOR_PICKUP, ShipmentStatus.PICKED_UP, ShipmentStatus.IN_TRANSIT, ShipmentStatus.FAILED],
      READY_FOR_PICKUP: [ShipmentStatus.PICKED_UP, ShipmentStatus.IN_TRANSIT, ShipmentStatus.FAILED],
      PICKED_UP: [ShipmentStatus.IN_TRANSIT, ShipmentStatus.OUT_FOR_DELIVERY, ShipmentStatus.FAILED],
      IN_TRANSIT: [ShipmentStatus.OUT_FOR_DELIVERY, ShipmentStatus.DELIVERED, ShipmentStatus.FAILED, ShipmentStatus.RETURNED],
      OUT_FOR_DELIVERY: [ShipmentStatus.DELIVERED, ShipmentStatus.FAILED, ShipmentStatus.RETURNED],
      DELIVERED: [], // Immutable terminal state
      FAILED: [ShipmentStatus.READY_FOR_PICKUP, ShipmentStatus.RETURNED],
      RETURNED: [],
    };

    const currentStatus = shipment.status;
    const allowed = allowedTransitions[currentStatus] || [];

    if (!allowed.includes(input.status)) {
      const error: any = new Error(`Invalid shipment status transition from "${currentStatus}" to "${input.status}".`);
      error.statusCode = 400;
      error.code = 'INVALID_STATUS_TRANSITION';
      throw error;
    }

    const updatedShipment = await shipmentRepository.updateShipmentStatus({
      shipmentId,
      status: input.status,
      location: input.location,
      description: input.description,
    });

    await logAuditEvent('SHIPMENT_STATUS_UPDATED', 'Shipment', userId, shipmentId, { newStatus: input.status }, ipAddress);
    return updatedShipment;
  }

  async getBuyerTracking(userId: string, orderNumber: string) {
    const order = await orderRepository.findOrderByNumber(orderNumber);

    if (!order) {
      const error: any = new Error('Order not found.');
      error.statusCode = 404;
      error.code = 'ORDER_NOT_FOUND';
      throw error;
    }

    if (order.buyerId !== userId) {
      const error: any = new Error('You are not authorized to view tracking for this order.');
      error.statusCode = 403;
      error.code = 'FORBIDDEN';
      throw error;
    }

    const shipments = await shipmentRepository.findShipmentsByOrderId(order.id);
    return {
      orderNumber: order.orderNumber,
      orderStatus: order.status,
      shipments,
    };
  }

  async getPublicTracking(shipmentNumber: string) {
    const shipment = await shipmentRepository.findShipmentByNumber(shipmentNumber);

    if (!shipment) {
      const error: any = new Error('Shipment not found.');
      error.statusCode = 404;
      error.code = 'SHIPMENT_NOT_FOUND';
      throw error;
    }

    // Expose only safe milestone info, preserving user/seller privacy
    return {
      shipmentNumber: shipment.shipmentNumber,
      status: shipment.status,
      shippingMethod: shipment.shippingMethod,
      courierPartner: shipment.courierPartner,
      trackingNumber: shipment.trackingNumber,
      estimatedDeliveryDate: shipment.estimatedDeliveryDate,
      shippedAt: shipment.shippedAt,
      deliveredAt: shipment.deliveredAt,
      events: shipment.events.map((e) => ({
        status: e.status,
        location: e.location,
        description: e.description,
        timestamp: e.timestamp,
      })),
    };
  }

  async getSellerShipments(userId: string, sellerId: string, page: number = 1, limit: number = 20, status?: ShipmentStatus) {
    return shipmentRepository.findSellerShipments(sellerId, { page, limit, status });
  }

  async confirmBuyerDelivery(userId: string, orderNumber: string, input?: ConfirmDeliveryInput, ipAddress?: string) {
    const order = await orderRepository.findOrderByNumber(orderNumber);

    if (!order) {
      const error: any = new Error('Order not found.');
      error.statusCode = 404;
      error.code = 'ORDER_NOT_FOUND';
      throw error;
    }

    if (order.buyerId !== userId) {
      const error: any = new Error('You are not authorized to confirm delivery for this order.');
      error.statusCode = 403;
      error.code = 'FORBIDDEN';
      throw error;
    }

    const shipments = await shipmentRepository.findShipmentsByOrderId(order.id);

    // Update all associated shipments to DELIVERED
    for (const shp of shipments) {
      if (shp.status !== ShipmentStatus.DELIVERED) {
        await shipmentRepository.updateShipmentStatus({
          shipmentId: shp.id,
          status: ShipmentStatus.DELIVERED,
          location: 'Buyer Destination / Campus Meetup',
          description: input?.note || 'Delivery confirmed by buyer.',
        });
      }
    }

    // Automatically transition Order to COMPLETED
    const updatedOrder = await orderRepository.updateOrderStatus(
      order.id,
      OrderStatus.COMPLETED,
      userId,
      'Delivery confirmed by buyer. Order completed.'
    );

    await logAuditEvent('DELIVERY_CONFIRMED', 'Order', userId, order.id, { orderNumber }, ipAddress);
    return updatedOrder;
  }
}

export const shipmentService = new ShipmentService();
