import { prisma } from '../config/prisma';
import { ShipmentStatus, ShippingMethod, Prisma } from '@prisma/client';
import { generateShipmentNumber } from '../utils/shipmentUtils';

export class ShipmentRepository {
  async createShipment(data: {
    orderId: string;
    sellerId: string;
    shippingMethod: ShippingMethod;
    courierPartner?: string;
    trackingNumber?: string;
    estimatedDeliveryDate?: Date;
    initialNote?: string;
  }) {
    const {
      orderId,
      sellerId,
      shippingMethod,
      courierPartner,
      trackingNumber,
      estimatedDeliveryDate,
      initialNote,
    } = data;

    const shipmentNumber = generateShipmentNumber();

    return prisma.shipment.create({
      data: {
        shipmentNumber,
        orderId,
        sellerId,
        shippingMethod,
        courierPartner: courierPartner || null,
        trackingNumber: trackingNumber || null,
        status: ShipmentStatus.PENDING,
        estimatedDeliveryDate: estimatedDeliveryDate || null,
        events: {
          create: {
            status: ShipmentStatus.PENDING,
            location: 'Seller Facility',
            description: initialNote || 'Shipment record generated by seller.',
          },
        },
      },
      include: {
        events: { orderBy: { timestamp: 'asc' } },
        order: {
          include: {
            buyer: { select: { id: true, firstName: true, lastName: true, email: true, phone: true } },
            items: true,
          },
        },
      },
    });
  }

  async findShipmentById(id: string) {
    return prisma.shipment.findUnique({
      where: { id },
      include: {
        events: { orderBy: { timestamp: 'asc' } },
        order: {
          include: {
            buyer: { select: { id: true, firstName: true, lastName: true, email: true, phone: true } },
            items: true,
          },
        },
      },
    });
  }

  async findShipmentByNumber(shipmentNumber: string) {
    return prisma.shipment.findUnique({
      where: { shipmentNumber },
      include: {
        events: { orderBy: { timestamp: 'asc' } },
        order: {
          include: {
            buyer: { select: { id: true, firstName: true, lastName: true, email: true, phone: true } },
            items: true,
          },
        },
      },
    });
  }

  async findShipmentsByOrderId(orderId: string) {
    return prisma.shipment.findMany({
      where: { orderId },
      include: {
        events: { orderBy: { timestamp: 'asc' } },
      },
      orderBy: { createdAt: 'desc' },
    });
  }

  async findSellerShipments(sellerId: string, options: { page: number; limit: number; status?: ShipmentStatus }) {
    const { page, limit, status } = options;
    const skip = (page - 1) * limit;

    const where: Prisma.ShipmentWhereInput = {
      sellerId,
      ...(status ? { status } : {}),
    };

    const [total, shipments] = await Promise.all([
      prisma.shipment.count({ where }),
      prisma.shipment.findMany({
        where,
        skip,
        take: limit,
        orderBy: { createdAt: 'desc' },
        include: {
          events: { orderBy: { timestamp: 'asc' } },
          order: {
            include: {
              buyer: { select: { id: true, firstName: true, lastName: true, email: true, phone: true } },
              items: true,
            },
          },
        },
      }),
    ]);

    const totalPages = Math.ceil(total / limit) || 1;

    return {
      shipments,
      pagination: {
        page,
        limit,
        total,
        totalPages,
        hasNextPage: page < totalPages,
        hasPreviousPage: page > 1,
      },
    };
  }

  async updateShipmentStatus(data: {
    shipmentId: string;
    status: ShipmentStatus;
    location?: string;
    description?: string;
  }) {
    const { shipmentId, status, location, description } = data;

    const isShipped = status === ShipmentStatus.IN_TRANSIT || status === ShipmentStatus.OUT_FOR_DELIVERY;
    const isDelivered = status === ShipmentStatus.DELIVERED;

    return prisma.shipment.update({
      where: { id: shipmentId },
      data: {
        status,
        ...(isShipped ? { shippedAt: new Date() } : {}),
        ...(isDelivered ? { deliveredAt: new Date() } : {}),
        events: {
          create: {
            status,
            location: location || null,
            description: description || `Status updated to ${status}.`,
          },
        },
      },
      include: {
        events: { orderBy: { timestamp: 'asc' } },
        order: {
          include: {
            buyer: true,
            items: true,
          },
        },
      },
    });
  }
}

export const shipmentRepository = new ShipmentRepository();
